wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.15
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683535073.241152
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 23
      4: 3.8.15
      5: 0.15.1
      8:
      - 3
      - 5
